services:
  case-db:
    image: postgres:15
    container_name: case-db
    environment:
      POSTGRES_DB: case_api_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./case-api
    container_name: case-api
    ports:
      - "3000:3000"
    env_file: ./case-api/.env
    depends_on:
      - case-db

  frontend:
    build:
      context: ./case-frontend
    container_name: case-frontend
    ports:
      - "5173:80"

volumes:
  pgdata:
